version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server/db:/app/db